[package]
name = "pixie-wasm"
version = "0.1.0"
authors = ["João Costa <jdpc557@gmail.com>"]

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew" }
pixie-rust = { git = "https://github.com/JD557/pixie-rust" }
csv = "1"
